version: '3.0'

services:

  nginx:
    image: nginx
    environment:
      - VIRTUAL_HOST=site.local
    depends_on:
      - php
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/
    networks:
      - frontend
      - backend

  php:
    build:
      context: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./:/var/www/html/:delegated
    networks:
      - backend

  postgres:
    image: postgres
    container_name: dolso_pg
    volumes:
      - dolso_pg_data:/var/lib/postgresql/data
    ports:
      - 127:0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: root
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    environment:
      - VIRTUAL_HOST=adminer.local
      - ADMINER_DEFAULT_SERVER=dolso_pg
    networks:
      - frontend
      - backend

volumes:
  dolso_pg_data:
#    external: true

networks:
  frontend:
    external:
      name: proxy_proxy
  backend: